[data]
root_dir = "../../datasets/hmdb51_motion/"
class_id_to_label_csv = "tc-clip/labels/hmdb_51_labels.csv"
train_class_text_json = "tc-clip/labels/custom/hmdb51_class_texts.json"
val_root_dir = "../../datasets/hmdb51/"
val_manifest = "tc-clip/datasets_splits/hmdb_splits/val1.txt"
val_class_id_to_label_csv = "tc-clip/labels/hmdb_51_labels.csv"
val_class_text_json = "tc-clip/labels/custom/hmdb51_class_texts.json"