[data]
root_dir = "../../datasets/UCF101_motion/"
class_id_to_label_csv = "tc-clip/labels/ucf_101_labels.csv"
val_root_dir = "../../datasets/UCF101/"
val_manifest = "tc-clip/datasets_splits/ucf_splits/val1.txt"
val_class_id_to_label_csv = "tc-clip/labels/ucf_101_labels.csv"

[pretrained]
pretrained_ckpt = "out/checkpoint_epoch_026_loss0.6188.pt"

[finetune]
temporal_mixup_prob = 0.5
temporal_mixup_y_min = 0.35
temporal_mixup_y_max = 0.65
lambda_rep_mix = 0.1
