[data]
root_dir = "../../datasets/UCF101_motion/"
class_id_to_label_csv = "tc-clip/labels/ucf_101_labels.csv"
train_class_text_json = "tc-clip/labels/custom/ucf101_motion_texts.json"
val_root_dir = "../../datasets/UCF101/"
val_manifest = "tc-clip/datasets_splits/ucf_splits/val1.txt"
val_class_id_to_label_csv = "tc-clip/labels/ucf_101_labels.csv"
val_class_text_json = "tc-clip/labels/custom/ucf101_motion_texts.json"